//
// Created by Fu_zh on 2022/9/9.
//

#ifndef OBJECT_ORIENTED_PROGRAMMING_PRACTICE_TEMPLATE_INHERIT_H
#define OBJECT_ORIENTED_PROGRAMMING_PRACTICE_TEMPLATE_INHERIT_H


class template_inherit {

};


#endif //OBJECT_ORIENTED_PROGRAMMING_PRACTICE_TEMPLATE_INHERIT_H
